package id.universenetwork.utilities.Bukkit.Hooks.SlimefunAddons.InfinityExpansion.Items.Machines;

import id.universenetwork.utilities.Bukkit.Libraries.InfinityLib.Machines.MachineBlock;
import id.universenetwork.utilities.Bukkit.Libraries.InfinityLib.Machines.MachineLore;
import io.github.thebusybiscuit.slimefun4.api.items.SlimefunItemStack;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;

import java.util.EnumMap;

import static id.universenetwork.utilities.Bukkit.Hooks.SlimefunAddons.Addons.addon;
import static id.universenetwork.utilities.Bukkit.Hooks.SlimefunAddons.InfinityExpansion.Groups.Groups.*;
import static id.universenetwork.utilities.Bukkit.Hooks.SlimefunAddons.InfinityExpansion.Items.Blocks.InfinityWorkbench.TYPE;
import static id.universenetwork.utilities.Bukkit.Hooks.SlimefunAddons.InfinityExpansion.Items.Materials.Materials.*;
import static id.universenetwork.utilities.Bukkit.Hooks.SlimefunAddons.InfinityExpansion.Items.SlimefunExtension.ADVANCED_GEO_MINER;
import static io.github.thebusybiscuit.slimefun4.api.recipes.RecipeType.ENHANCED_CRAFTING_TABLE;
import static io.github.thebusybiscuit.slimefun4.implementation.SlimefunItems.*;

@lombok.experimental.UtilityClass
public final class Machines {
    public static final SlimefunItemStack COBBLE_PRESS = new SlimefunItemStack("COBBLE_PRESS", Material.SMOOTH_STONE, "&8Cobble Press", "&7Compresses cobblestone more efficiently", "", MachineLore.energyPerSecond(120));
    public static final SlimefunItemStack RESOURCE_SYNTHESIZER = new SlimefunItemStack("RESOURCE_SYNTHESIZER", Material.LODESTONE, "&6Resource Synthesizer", "&7Creates resources by combining 2 Singularities", "", MachineLore.energy(1_000_000) + "per use");
    public static final SlimefunItemStack BASIC_GROWER = new SlimefunItemStack("BASIC_VIRTUAL_FARM", Material.GRASS_BLOCK, "&9Basic &aVirtual Farm", "&7Automatically grows, harvests, and replants crops", "", MachineLore.speed(1), MachineLore.energyPerSecond(18));
    public static final SlimefunItemStack ADVANCED_GROWER = new SlimefunItemStack("ADVANCED_VIRTUAL_FARM", Material.CRIMSON_NYLIUM, "&cAdvanced &aVirtual Farm", "&7Automatically grows, harvests, and replants crops", "", MachineLore.speed(5), MachineLore.energyPerSecond(90));
    public static final SlimefunItemStack INFINITY_GROWER = new SlimefunItemStack("INFINITY_VIRTUAL_FARM", Material.WARPED_NYLIUM, "&bInfinity &aVirtual Farm", "&7Automatically grows, harvests, and replants crops", "", MachineLore.speed(25), MachineLore.energyPerSecond(900));
    public static final SlimefunItemStack BASIC_TREE = new SlimefunItemStack("BASIC_TREE_GROWER", Material.STRIPPED_OAK_WOOD, "&9Basic &2Tree Grower", "&7Automatically grows, harvests, and replants trees", "", MachineLore.speed(1), MachineLore.energyPerSecond(36));
    public static final SlimefunItemStack ADVANCED_TREE = new SlimefunItemStack("ADVANCED_TREE_GROWER", Material.STRIPPED_ACACIA_WOOD, "&cAdvanced &2Tree Grower", "&7Automatically grows, harvests, and replants trees", "", MachineLore.speed(5), MachineLore.energyPerSecond(180));
    public static final SlimefunItemStack INFINITY_TREE = new SlimefunItemStack("INFINITY_TREE_GROWER", Material.STRIPPED_WARPED_HYPHAE, "&bInfinity &2Tree Grower", "&7Automatically grows, harvests, and replants trees", "", MachineLore.speed(25), MachineLore.energyPerSecond(1800));
    public static final SlimefunItemStack EXTREME_FREEZER = new SlimefunItemStack("EXTREME_FREEZER", Material.LIGHT_BLUE_CONCRETE, "&bExtreme Freezer", "&7Converts ice into coolant", "", MachineLore.energyPerSecond(90));
    public static final SlimefunItemStack DUST_EXTRACTOR = new SlimefunItemStack("DUST_EXTRACTOR", Material.FURNACE, "&8Dust Extractor", "&7Converts cobble into dusts", "", MachineLore.speed(1), MachineLore.energyPerSecond(240));
    public static final SlimefunItemStack INFINITY_DUST_EXTRACTOR = new SlimefunItemStack("INFINITY_DUST_EXTRACTOR", Material.FURNACE, "&bInfinity &8Dust Extractor", "&7Converts cobble into dusts", "", MachineLore.speed(16), MachineLore.energyPerSecond(7200));
    public static final SlimefunItemStack INGOT_FORMER = new SlimefunItemStack("INGOT_FORMER", Material.FURNACE, "&8Ingot Former", "&7Forms ingots from dusts", "", MachineLore.speed(1), MachineLore.energyPerSecond(240));
    public static final SlimefunItemStack INFINITY_INGOT_FORMER = new SlimefunItemStack("INFINITY_INGOT_FORMER", Material.FURNACE, "&bInfinity &8Ingot Former", "&7Forms ingots from dusts", "", MachineLore.speed(16), MachineLore.energyPerSecond(7200));
    public static final SlimefunItemStack URANIUM_EXTRACTOR = new SlimefunItemStack("URANIUM_EXTRACTOR", Material.LIME_CONCRETE, "&aUranium Extractor", "&7Converts cobble into uranium", "", MachineLore.energyPerSecond(240));
    public static final SlimefunItemStack DECOMPRESSOR = new SlimefunItemStack("DECOMPRESSOR", Material.TARGET, "&7Decompressor", "&7Reduces blocks to their base material", "", MachineLore.energyPerSecond(60));
    public static final SlimefunItemStack BASIC_COBBLE = new SlimefunItemStack("BASIC_COBBLE_GEN", Material.SMOOTH_STONE, "&9Basic &8Cobble Generator", "", MachineLore.speed(1), MachineLore.energyPerSecond(24));
    public static final SlimefunItemStack ADVANCED_COBBLE = new SlimefunItemStack("ADVANCED_COBBLE_GEN", Material.SMOOTH_STONE, "&cAdvanced &8Cobble Generator", "", MachineLore.speed(4), MachineLore.energyPerSecond(120));
    public static final SlimefunItemStack INFINITY_COBBLE = new SlimefunItemStack("INFINITY_COBBLE_GEN", Material.SMOOTH_STONE, "&cInfinity &8Cobble Generator", "", MachineLore.speed(64), MachineLore.energyPerSecond(800));
    public static final SlimefunItemStack BASIC_OBSIDIAN = new SlimefunItemStack("BASIC_OBSIDIAN_GEN", Material.SMOOTH_STONE, "&8Obsidian Generator", "", MachineLore.speed(1), MachineLore.energyPerSecond(240));
    public static final SlimefunItemStack SINGULARITY_CONSTRUCTOR = new SlimefunItemStack("SINGULARITY_CONSTRUCTOR", Material.QUARTZ_BRICKS, "&fSingularity Constructor", "&7Condenses large amounts of resources", "", MachineLore.speed(1), MachineLore.energyPerSecond(120));
    public static final SlimefunItemStack INFINITY_CONSTRUCTOR = new SlimefunItemStack("INFINITY_CONSTRUCTOR", Material.CHISELED_QUARTZ_BLOCK, "&bInfinity &fConstructor", "&7Quickly condenses large amounts of resources", "", MachineLore.speed(64), MachineLore.energyPerSecond(1200));
    public static final SlimefunItemStack STONEWORKS_FACTORY = new SlimefunItemStack("STONEWORKS_FACTORY", Material.BLAST_FURNACE, "&8Stoneworks Factory", "&7Generates cobblestone and processes it into various materials", "", MachineLore.energyPerSecond(240));
    public static final SlimefunItemStack VOID_HARVESTER = new SlimefunItemStack("VOID_HARVESTER", Material.OBSIDIAN, "&8Void Harvester", "&7Slowly harvests &8Void &7Bits from nothing...", "", MachineLore.speed(1), MachineLore.energyPerSecond(120));
    public static final SlimefunItemStack INFINITE_VOID_HARVESTER = new SlimefunItemStack("INFINITE_VOID_HARVESTER", Material.CRYING_OBSIDIAN, "&bInfinite &8Void Harvester", "&7Harvests &8Void &7Bits from nothing...", "", MachineLore.speed(64), MachineLore.energyPerSecond(12000));
    static final int BEDROCK_ENERGY = 10_000;
    public static final SlimefunItemStack POWERED_BEDROCK = new SlimefunItemStack("POWERED_BEDROCK", Material.NETHERITE_BLOCK, "&4Powered Bedrock", "&7When powered, transforms into a bedrock", "&7Will revert once unpowered or broken", "", MachineLore.energyPerSecond(BEDROCK_ENERGY));
    static final int GEO_QUARRY_INTERVAL = 400;
    static final int GEO_QUARRY_ENERGY = 450;
    public static final SlimefunItemStack GEO_QUARRY = new SlimefunItemStack("GEO_QUARRY", Material.QUARTZ_BRICKS, "&fGeo Quarry", "&7Slowly harvests geo resources from the void using power", "", MachineLore.energyPerSecond(GEO_QUARRY_ENERGY));
    static final int GEAR_TRANSFORMER_ENERGY = 12000;
    public static final SlimefunItemStack GEAR_TRANSFORMER = new SlimefunItemStack("GEAR_TRANSFORMER", Material.EMERALD_BLOCK, "&7Gear Transformer", "&7Changes the material of vanilla tools and gear", "", MachineLore.energy(GEAR_TRANSFORMER_ENERGY) + "Per Use");

    public static void setup() {
        new VoidHarvester(ADVANCED_MACHINES, VOID_HARVESTER, ENHANCED_CRAFTING_TABLE, new ItemStack[]{TITANIUM, TITANIUM, TITANIUM, MACHINE_PLATE, GEO_MINER, MACHINE_PLATE, MACHINE_CIRCUIT, MACHINE_CORE, MACHINE_CIRCUIT}, 1).energyPerTick(120).register(addon);
        new VoidHarvester(INFINITY_CHEAT, INFINITE_VOID_HARVESTER, TYPE, new ItemStack[]{MACHINE_PLATE, MACHINE_PLATE, MACHINE_PLATE, MACHINE_PLATE, MACHINE_PLATE, MACHINE_PLATE, MAGNONIUM, VOID_INGOT, VOID_INGOT, VOID_INGOT, VOID_INGOT, MAGNONIUM, MAGNONIUM, VOID_INGOT, INFINITE_CIRCUIT, INFINITE_CIRCUIT, VOID_INGOT, MAGNONIUM, MAGNONIUM, VOID_INGOT, VOID_HARVESTER, VOID_HARVESTER, VOID_INGOT, MAGNONIUM, MAGNONIUM, VOID_INGOT, VOID_INGOT, VOID_INGOT, VOID_INGOT, MAGNONIUM, MACHINE_PLATE, MACHINE_PLATE, MACHINE_PLATE, MACHINE_PLATE, MACHINE_PLATE, MACHINE_PLATE}, 64).energyPerTick(12000).register(addon);
        new StoneworksFactory(ADVANCED_MACHINES, STONEWORKS_FACTORY, ENHANCED_CRAFTING_TABLE, new ItemStack[]{MAGSTEEL_PLATE, BASIC_COBBLE, MAGSTEEL_PLATE, ELECTRIC_FURNACE_3, MACHINE_CIRCUIT, ELECTRIC_ORE_GRINDER, MAGSTEEL_PLATE, ELECTRIC_PRESS, MAGSTEEL_PLATE}).energyPerTick(240).register(addon);
        new SingularityConstructor(ADVANCED_MACHINES, SINGULARITY_CONSTRUCTOR, ENHANCED_CRAFTING_TABLE, new ItemStack[]{MAGSTEEL, MAGSTEEL, MAGSTEEL, MACHINE_PLATE, CARBON_PRESS_3, MACHINE_PLATE, MACHINE_CIRCUIT, MACHINE_CORE, MACHINE_CIRCUIT}).speed(1).energyPerTick(120).register(addon);
        new SingularityConstructor(INFINITY_CHEAT, INFINITY_CONSTRUCTOR, TYPE, new ItemStack[]{null, MACHINE_PLATE, MACHINE_PLATE, MACHINE_PLATE, MACHINE_PLATE, null, null, VOID_INGOT, INFINITE_CIRCUIT, INFINITE_CIRCUIT, VOID_INGOT, null, null, VOID_INGOT, SINGULARITY_CONSTRUCTOR, SINGULARITY_CONSTRUCTOR, VOID_INGOT, null, null, VOID_INGOT, SINGULARITY_CONSTRUCTOR, SINGULARITY_CONSTRUCTOR, VOID_INGOT, null, null, INFINITE_INGOT, INFINITE_CORE, INFINITE_CORE, INFINITE_INGOT, null, INFINITE_INGOT, INFINITE_INGOT, INFINITE_INGOT, INFINITE_INGOT, INFINITE_INGOT, INFINITE_INGOT}).speed(64).energyPerTick(1200).register(addon);
        new ResourceSynthesizer(ADVANCED_MACHINES, RESOURCE_SYNTHESIZER, ENHANCED_CRAFTING_TABLE, new ItemStack[]{ADAMANTITE, ADAMANTITE, ADAMANTITE, MACHINE_PLATE, REINFORCED_FURNACE, MACHINE_PLATE, MACHINE_PLATE, MACHINE_CORE, MACHINE_PLATE}).recipes(new SlimefunItemStack[]{IRON_SINGULARITY, COAL_SINGULARITY, new SlimefunItemStack(REINFORCED_ALLOY_INGOT, 32), IRON_SINGULARITY, REDSTONE_SINGULARITY, new SlimefunItemStack(REDSTONE_ALLOY, 32), DIAMOND_SINGULARITY, COAL_SINGULARITY, new SlimefunItemStack(CARBONADO, 16), GOLD_SINGULARITY, EMERALD_SINGULARITY, new SlimefunItemStack(BLISTERING_INGOT_3, 16), COPPER_SINGULARITY, ZINC_SINGULARITY, new SlimefunItemStack(ELECTRO_MAGNET, 64), IRON_SINGULARITY, QUARTZ_SINGULARITY, new SlimefunItemStack(SOLAR_PANEL, 64)}).energyPerTick(1_000_000).register(addon);
        new PoweredBedrock(INFINITY_CHEAT, POWERED_BEDROCK, TYPE, new ItemStack[]{COBBLE_5, COBBLE_5, COBBLE_5, COBBLE_5, COBBLE_5, COBBLE_5, COBBLE_5, MACHINE_PLATE, VOID_INGOT, VOID_INGOT, MACHINE_PLATE, COBBLE_5, COBBLE_5, VOID_INGOT, ENERGIZED_CAPACITOR, ENERGIZED_CAPACITOR, VOID_INGOT, COBBLE_5, COBBLE_5, VOID_INGOT, INFINITE_CORE, INFINITE_CIRCUIT, VOID_INGOT, COBBLE_5, COBBLE_5, MACHINE_PLATE, VOID_INGOT, VOID_INGOT, MACHINE_PLATE, COBBLE_5, COBBLE_5, COBBLE_5, COBBLE_5, COBBLE_5, COBBLE_5, COBBLE_5}, BEDROCK_ENERGY).register(addon);
        new MaterialGenerator(BASIC_MACHINES, BASIC_COBBLE, ENHANCED_CRAFTING_TABLE, new ItemStack[]{MAGSTEEL, new ItemStack(Material.DIAMOND_PICKAXE), MAGSTEEL, new ItemStack(Material.WATER_BUCKET), COBBLE_2, new ItemStack(Material.LAVA_BUCKET), MAGSTEEL, MACHINE_CIRCUIT, MAGSTEEL}).material(Material.COBBLESTONE).speed(1).energyPerTick(24).register(addon);
        new MaterialGenerator(ADVANCED_MACHINES, ADVANCED_COBBLE, ENHANCED_CRAFTING_TABLE, new ItemStack[]{MAGSTEEL_PLATE, BASIC_COBBLE, MAGSTEEL_PLATE, new ItemStack(Material.WATER_BUCKET), COBBLE_3, new ItemStack(Material.LAVA_BUCKET), MACHINE_CIRCUIT, BASIC_COBBLE, MACHINE_CIRCUIT}).material(Material.COBBLESTONE).speed(4).energyPerTick(75).register(addon);
        new MaterialGenerator(INFINITY_CHEAT, INFINITY_COBBLE, TYPE, new ItemStack[]{VOID_INGOT, VOID_INGOT, VOID_INGOT, VOID_INGOT, VOID_INGOT, VOID_INGOT, VOID_INGOT, ADVANCED_COBBLE, ADVANCED_COBBLE, ADVANCED_COBBLE, ADVANCED_COBBLE, VOID_INGOT, VOID_INGOT, ADVANCED_COBBLE, ADVANCED_COBBLE, ADVANCED_COBBLE, ADVANCED_COBBLE, VOID_INGOT, VOID_INGOT, ADVANCED_COBBLE, ADVANCED_COBBLE, ADVANCED_COBBLE, ADVANCED_COBBLE, VOID_INGOT, VOID_INGOT, ADVANCED_COBBLE, ADVANCED_COBBLE, ADVANCED_COBBLE, ADVANCED_COBBLE, VOID_INGOT, VOID_INGOT, VOID_INGOT, VOID_INGOT, VOID_INGOT, VOID_INGOT, VOID_INGOT}).material(Material.COBBLESTONE).speed(64).energyPerTick(800).register(addon);
        new MaterialGenerator(ADVANCED_MACHINES, BASIC_OBSIDIAN, ENHANCED_CRAFTING_TABLE, new ItemStack[]{FLUID_PUMP, PROGRAMMABLE_ANDROID_MINER, FLUID_PUMP, new ItemStack(Material.DISPENSER), VOID_INGOT, new ItemStack(Material.DISPENSER), MACHINE_CIRCUIT, ADVANCED_COBBLE, MACHINE_CIRCUIT}).material(Material.OBSIDIAN).speed(1).energyPerTick(240).register(addon);
        EnumMap<Material, ItemStack[]> crops = new EnumMap<>(Material.class);
        crops.put(Material.WHEAT_SEEDS, new ItemStack[]{new ItemStack(Material.WHEAT, 2)});
        crops.put(Material.CARROT, new ItemStack[]{new ItemStack(Material.CARROT, 2)});
        crops.put(Material.POTATO, new ItemStack[]{new ItemStack(Material.POTATO, 2)});
        crops.put(Material.BEETROOT_SEEDS, new ItemStack[]{new ItemStack(Material.BEETROOT, 2)});
        crops.put(Material.PUMPKIN_SEEDS, new ItemStack[]{new ItemStack(Material.PUMPKIN)});
        crops.put(Material.MELON_SEEDS, new ItemStack[]{new ItemStack(Material.MELON)});
        crops.put(Material.SUGAR_CANE, new ItemStack[]{new ItemStack(Material.SUGAR_CANE, 2)});
        crops.put(Material.COCOA_BEANS, new ItemStack[]{new ItemStack(Material.COCOA_BEANS, 2)});
        crops.put(Material.CACTUS, new ItemStack[]{new ItemStack(Material.CACTUS, 2)});
        crops.put(Material.BAMBOO, new ItemStack[]{new ItemStack(Material.BAMBOO, 6)});
        crops.put(Material.CHORUS_FLOWER, new ItemStack[]{new ItemStack(Material.CHORUS_FRUIT, 6)});
        crops.put(Material.NETHER_WART, new ItemStack[]{new ItemStack(Material.NETHER_WART, 2)});
        new GrowingMachine(BASIC_MACHINES, BASIC_GROWER, ENHANCED_CRAFTING_TABLE, new ItemStack[]{new ItemStack(Material.GLASS), new ItemStack(Material.GLASS), new ItemStack(Material.GLASS), MAGSTEEL, new ItemStack(Material.DIAMOND_HOE), MAGSTEEL, MACHINE_CIRCUIT, new ItemStack(Material.GRASS_BLOCK), MACHINE_CIRCUIT}).recipes(crops).ticksPerOutput(300).energyPerTick(18).register(addon);
        new GrowingMachine(ADVANCED_MACHINES, ADVANCED_GROWER, ENHANCED_CRAFTING_TABLE, new ItemStack[]{HARDENED_GLASS, HARDENED_GLASS, HARDENED_GLASS, MAGNONIUM, BASIC_GROWER, MAGNONIUM, MACHINE_CIRCUIT, MACHINE_CORE, MACHINE_CIRCUIT}).recipes(crops).ticksPerOutput(60).energyPerTick(90).register(addon);
        new GrowingMachine(INFINITY_CHEAT, INFINITY_GROWER, TYPE, new ItemStack[]{new ItemStack(Material.GLASS), new ItemStack(Material.GLASS), new ItemStack(Material.GLASS), new ItemStack(Material.GLASS), new ItemStack(Material.GLASS), new ItemStack(Material.GLASS), new ItemStack(Material.GLASS), null, null, null, null, new ItemStack(Material.GLASS), new ItemStack(Material.GLASS), null, null, null, null, new ItemStack(Material.GLASS), new ItemStack(Material.GLASS), new ItemStack(Material.GRASS_BLOCK), new ItemStack(Material.GRASS_BLOCK), new ItemStack(Material.GRASS_BLOCK), new ItemStack(Material.GRASS_BLOCK), new ItemStack(Material.GLASS), MACHINE_PLATE, CROP_GROWTH_ACCELERATOR_2, ADVANCED_GROWER, ADVANCED_GROWER, CROP_GROWTH_ACCELERATOR_2, MACHINE_PLATE, MACHINE_PLATE, INFINITE_CIRCUIT, INFINITE_CORE, INFINITE_CORE, INFINITE_CIRCUIT, MACHINE_PLATE}).recipes(crops).ticksPerOutput(12).energyPerTick(900).register(addon);
        EnumMap<Material, ItemStack[]> trees = new EnumMap<>(Material.class);
        trees.put(Material.OAK_SAPLING, new ItemStack[]{new ItemStack(Material.OAK_LEAVES, 8), new ItemStack(Material.OAK_LOG, 6), new ItemStack(Material.STICK), new ItemStack(Material.APPLE)});
        trees.put(Material.SPRUCE_SAPLING, new ItemStack[]{new ItemStack(Material.SPRUCE_LEAVES, 8), new ItemStack(Material.SPRUCE_LOG, 6), new ItemStack(Material.STICK, 2)});
        trees.put(Material.DARK_OAK_SAPLING, new ItemStack[]{new ItemStack(Material.DARK_OAK_LEAVES, 8), new ItemStack(Material.DARK_OAK_LOG, 6), new ItemStack(Material.APPLE)});
        trees.put(Material.BIRCH_SAPLING, new ItemStack[]{new ItemStack(Material.BIRCH_LEAVES, 8), new ItemStack(Material.BIRCH_LOG, 6)});
        trees.put(Material.ACACIA_SAPLING, new ItemStack[]{new ItemStack(Material.ACACIA_LEAVES, 8), new ItemStack(Material.ACACIA_LOG, 6)});
        trees.put(Material.JUNGLE_SAPLING, new ItemStack[]{new ItemStack(Material.JUNGLE_LEAVES, 8), new ItemStack(Material.JUNGLE_LOG, 6), new ItemStack(Material.COCOA_BEANS)});
        trees.put(Material.WARPED_FUNGUS, new ItemStack[]{new ItemStack(Material.WARPED_HYPHAE, 8), new ItemStack(Material.WARPED_STEM, 6), new ItemStack(Material.SHROOMLIGHT)});
        trees.put(Material.CRIMSON_FUNGUS, new ItemStack[]{new ItemStack(Material.CRIMSON_HYPHAE, 8), new ItemStack(Material.CRIMSON_STEM, 6), new ItemStack(Material.WEEPING_VINES)});
        new GrowingMachine(BASIC_MACHINES, BASIC_TREE, ENHANCED_CRAFTING_TABLE, new ItemStack[]{new ItemStack(Material.GLASS), new ItemStack(Material.GLASS), new ItemStack(Material.GLASS), MAGSTEEL, new ItemStack(Material.PODZOL), MAGSTEEL, MACHINE_CIRCUIT, BASIC_GROWER, MACHINE_CIRCUIT}).recipes(trees).ticksPerOutput(600).energyPerTick(36).register(addon);
        new GrowingMachine(ADVANCED_MACHINES, ADVANCED_TREE, ENHANCED_CRAFTING_TABLE, new ItemStack[]{HARDENED_GLASS, HARDENED_GLASS, HARDENED_GLASS, MAGNONIUM, BASIC_TREE, MAGNONIUM, MACHINE_CIRCUIT, MACHINE_CORE, MACHINE_CIRCUIT}).recipes(trees).ticksPerOutput(120).energyPerTick(180).register(addon);
        new GrowingMachine(INFINITY_CHEAT, INFINITY_TREE, TYPE, new ItemStack[]{new ItemStack(Material.GLASS), new ItemStack(Material.GLASS), new ItemStack(Material.GLASS), new ItemStack(Material.GLASS), new ItemStack(Material.GLASS), new ItemStack(Material.GLASS), new ItemStack(Material.GLASS), TREE_GROWTH_ACCELERATOR, null, null, TREE_GROWTH_ACCELERATOR, new ItemStack(Material.GLASS), new ItemStack(Material.GLASS), ADVANCED_TREE, null, null, ADVANCED_TREE, new ItemStack(Material.GLASS), new ItemStack(Material.GLASS), TREE_GROWTH_ACCELERATOR, null, null, TREE_GROWTH_ACCELERATOR, new ItemStack(Material.GLASS), MACHINE_PLATE, new ItemStack(Material.PODZOL), new ItemStack(Material.PODZOL), new ItemStack(Material.PODZOL), new ItemStack(Material.PODZOL), MACHINE_PLATE, MACHINE_PLATE, INFINITE_CIRCUIT, INFINITE_CORE, INFINITE_CORE, INFINITE_CIRCUIT, MACHINE_PLATE}).recipes(trees).ticksPerOutput(24).energyPerTick(1800).register(addon);
        new MachineBlock(ADVANCED_MACHINES, EXTREME_FREEZER, ENHANCED_CRAFTING_TABLE, new ItemStack[]{FREEZER_2, FREEZER_2, FREEZER_2, new ItemStack(Material.WATER_BUCKET), FLUID_PUMP, new ItemStack(Material.WATER_BUCKET), MACHINE_CIRCUIT, MACHINE_CORE, MACHINE_CIRCUIT}).addRecipe(NETHER_ICE_COOLANT_CELL, new ItemStack(Material.MAGMA_BLOCK, 2)).ticksPerOutput(1).addRecipe(REACTOR_COOLANT_CELL, new ItemStack(Material.ICE, 2)).energyPerTick(90).register(addon);
        RandomizedItemStack twoDust = new RandomizedItemStack(new SlimefunItemStack(COPPER_DUST, 2), new SlimefunItemStack(ZINC_DUST, 2), new SlimefunItemStack(TIN_DUST, 2), new SlimefunItemStack(ALUMINUM_DUST, 2), new SlimefunItemStack(LEAD_DUST, 2), new SlimefunItemStack(SILVER_DUST, 2), new SlimefunItemStack(GOLD_DUST, 2), new SlimefunItemStack(IRON_DUST, 2), new SlimefunItemStack(MAGNESIUM_DUST, 2));
        new MachineBlock(ADVANCED_MACHINES, DUST_EXTRACTOR, ENHANCED_CRAFTING_TABLE, new ItemStack[]{ELECTRIC_ORE_GRINDER_2, ELECTRIC_GOLD_PAN_3, ELECTRIC_DUST_WASHER_3, ELECTRIC_ORE_GRINDER_2, ELECTRIC_GOLD_PAN_3, ELECTRIC_DUST_WASHER_3, MACHINE_CIRCUIT, MACHINE_CORE, MACHINE_CIRCUIT,}).ticksPerOutput(1).addRecipe(twoDust, new ItemStack(Material.COBBLESTONE, 4)).addRecipe(twoDust, new ItemStack(Material.ANDESITE, 4)).addRecipe(twoDust, new ItemStack(Material.STONE, 4)).addRecipe(twoDust, new ItemStack(Material.DIORITE, 4)).addRecipe(twoDust, new ItemStack(Material.GRANITE, 4)).energyPerTick(240).register(addon);
        RandomizedItemStack sixtyFourDust = new RandomizedItemStack(new SlimefunItemStack(COPPER_DUST, 64), new SlimefunItemStack(ZINC_DUST, 64), new SlimefunItemStack(TIN_DUST, 64), new SlimefunItemStack(ALUMINUM_DUST, 64), new SlimefunItemStack(LEAD_DUST, 64), new SlimefunItemStack(SILVER_DUST, 64), new SlimefunItemStack(GOLD_DUST, 64), new SlimefunItemStack(IRON_DUST, 64), new SlimefunItemStack(MAGNESIUM_DUST, 64));
        new MachineBlock(INFINITY_CHEAT, INFINITY_DUST_EXTRACTOR, TYPE, new ItemStack[]{VOID_INGOT, VOID_INGOT, VOID_INGOT, VOID_INGOT, VOID_INGOT, VOID_INGOT, VOID_INGOT, INFINITE_INGOT, INFINITE_CIRCUIT, INFINITE_CIRCUIT, INFINITE_INGOT, VOID_INGOT, VOID_INGOT, INFINITE_INGOT, DUST_EXTRACTOR, DUST_EXTRACTOR, INFINITE_INGOT, VOID_INGOT, VOID_INGOT, INFINITE_INGOT, DUST_EXTRACTOR, DUST_EXTRACTOR, INFINITE_INGOT, VOID_INGOT, VOID_INGOT, INFINITE_INGOT, DUST_EXTRACTOR, DUST_EXTRACTOR, INFINITE_INGOT, VOID_INGOT, VOID_INGOT, VOID_INGOT, VOID_INGOT, VOID_INGOT, VOID_INGOT, VOID_INGOT,}).addRecipe(sixtyFourDust, new ItemStack(Material.COBBLESTONE, 64)).addRecipe(sixtyFourDust, new ItemStack(Material.ANDESITE, 64)).addRecipe(sixtyFourDust, new ItemStack(Material.STONE, 64)).addRecipe(sixtyFourDust, new ItemStack(Material.DIORITE, 64)).addRecipe(sixtyFourDust, new ItemStack(Material.GRANITE, 64)).ticksPerOutput(1).energyPerTick(7200).register(addon);
        new MachineBlock(ADVANCED_MACHINES, COBBLE_PRESS, ENHANCED_CRAFTING_TABLE, new ItemStack[]{MACHINE_PLATE, COBBLE_3, MACHINE_PLATE, ELECTRIC_PRESS_2, ELECTRIC_PRESS_2, ELECTRIC_PRESS_2, MACHINE_PLATE, COBBLE_3, MACHINE_PLATE}).addRecipe(new SlimefunItemStack(COBBLE_1, 8), new ItemStack(Material.COBBLESTONE, 64)).addRecipe(new SlimefunItemStack(COBBLE_2, 8), new SlimefunItemStack(COBBLE_1, 64)).addRecipe(new SlimefunItemStack(COBBLE_3, 8), new SlimefunItemStack(COBBLE_2, 64)).addRecipe(new SlimefunItemStack(COBBLE_4, 8), new SlimefunItemStack(COBBLE_3, 64)).addRecipe(new SlimefunItemStack(COBBLE_5, 8), new SlimefunItemStack(COBBLE_4, 64)).ticksPerOutput(1).energyPerTick(120).register(addon);
        new MachineBlock(ADVANCED_MACHINES, INGOT_FORMER, ENHANCED_CRAFTING_TABLE, new ItemStack[]{ELECTRIC_INGOT_FACTORY_2, ELECTRIC_INGOT_FACTORY_2, ELECTRIC_INGOT_FACTORY_2, ELECTRIC_INGOT_FACTORY_2, ELECTRIC_INGOT_FACTORY_2, ELECTRIC_INGOT_FACTORY_2, MACHINE_CIRCUIT, MACHINE_CORE, MACHINE_CIRCUIT,}).addRecipe(new SlimefunItemStack(COPPER_INGOT, 4), new SlimefunItemStack(COPPER_DUST, 8)).addRecipe(new SlimefunItemStack(ZINC_INGOT, 4), new SlimefunItemStack(ZINC_DUST, 8)).addRecipe(new SlimefunItemStack(TIN_INGOT, 4), new SlimefunItemStack(TIN_DUST, 8)).addRecipe(new SlimefunItemStack(ALUMINUM_INGOT, 4), new SlimefunItemStack(ALUMINUM_DUST, 8)).addRecipe(new SlimefunItemStack(LEAD_INGOT, 4), new SlimefunItemStack(LEAD_DUST, 8)).addRecipe(new SlimefunItemStack(SILVER_INGOT, 4), new SlimefunItemStack(SILVER_DUST, 8)).addRecipe(new SlimefunItemStack(GOLD_24K, 1), new SlimefunItemStack(GOLD_DUST, 8)).addRecipe(new ItemStack(Material.IRON_INGOT, 4), new SlimefunItemStack(IRON_DUST, 8)).addRecipe(new SlimefunItemStack(MAGNESIUM_INGOT, 4), new SlimefunItemStack(MAGNESIUM_DUST, 8)).ticksPerOutput(1).energyPerTick(240).register(addon);
        new MachineBlock(INFINITY_CHEAT, INFINITY_INGOT_FORMER, TYPE, new ItemStack[]{VOID_INGOT, VOID_INGOT, VOID_INGOT, VOID_INGOT, VOID_INGOT, VOID_INGOT, VOID_INGOT, INFINITE_INGOT, INFINITE_CIRCUIT, INFINITE_CIRCUIT, INFINITE_INGOT, VOID_INGOT, VOID_INGOT, INFINITE_INGOT, INGOT_FORMER, INGOT_FORMER, INFINITE_INGOT, VOID_INGOT, VOID_INGOT, INFINITE_INGOT, INGOT_FORMER, INGOT_FORMER, INFINITE_INGOT, VOID_INGOT, VOID_INGOT, INFINITE_INGOT, INGOT_FORMER, INGOT_FORMER, INFINITE_INGOT, VOID_INGOT, VOID_INGOT, VOID_INGOT, VOID_INGOT, VOID_INGOT, VOID_INGOT, VOID_INGOT,}).addRecipe(new SlimefunItemStack(COPPER_INGOT, 32), new SlimefunItemStack(COPPER_DUST, 64)).addRecipe(new SlimefunItemStack(ZINC_INGOT, 32), new SlimefunItemStack(ZINC_DUST, 64)).addRecipe(new SlimefunItemStack(TIN_INGOT, 32), new SlimefunItemStack(TIN_DUST, 64)).addRecipe(new SlimefunItemStack(ALUMINUM_INGOT, 32), new SlimefunItemStack(ALUMINUM_DUST, 64)).addRecipe(new SlimefunItemStack(LEAD_INGOT, 32), new SlimefunItemStack(LEAD_DUST, 64)).addRecipe(new SlimefunItemStack(SILVER_INGOT, 32), new SlimefunItemStack(SILVER_DUST, 64)).addRecipe(new SlimefunItemStack(GOLD_24K, 10), new SlimefunItemStack(GOLD_DUST, 64)).addRecipe(new ItemStack(Material.IRON_INGOT, 32), new SlimefunItemStack(IRON_DUST, 64)).addRecipe(new SlimefunItemStack(MAGNESIUM_INGOT, 32), new SlimefunItemStack(MAGNESIUM_DUST, 64)).ticksPerOutput(1).energyPerTick(7200).register(addon);
        new MachineBlock(ADVANCED_MACHINES, URANIUM_EXTRACTOR, ENHANCED_CRAFTING_TABLE, new ItemStack[]{ELECTRIC_ORE_GRINDER_2, ELECTRIC_ORE_GRINDER_2, ELECTRIC_ORE_GRINDER_2, ELECTRIC_GOLD_PAN_3, ELECTRIC_DUST_WASHER_3, ENHANCED_AUTO_CRAFTER, MACHINE_CIRCUIT, MACHINE_CORE, MACHINE_CIRCUIT,}).addRecipe(SMALL_URANIUM, new ItemStack(Material.COBBLESTONE, 4)).addRecipe(SMALL_URANIUM, new ItemStack(Material.ANDESITE, 4)).addRecipe(SMALL_URANIUM, new ItemStack(Material.STONE, 4)).addRecipe(SMALL_URANIUM, new ItemStack(Material.DIORITE, 4)).addRecipe(SMALL_URANIUM, new ItemStack(Material.GRANITE, 4)).ticksPerOutput(1).energyPerTick(240).register(addon);
        new MachineBlock(ADVANCED_MACHINES, DECOMPRESSOR, ENHANCED_CRAFTING_TABLE, new ItemStack[]{MAGSTEEL_PLATE, MAGSTEEL_PLATE, MAGSTEEL_PLATE, new ItemStack(Material.STICKY_PISTON), ELECTRIC_PRESS_2, new ItemStack(Material.STICKY_PISTON), MACHINE_CIRCUIT, MACHINE_CORE, MACHINE_CIRCUIT,}).addRecipe(new ItemStack(Material.EMERALD, 9), new ItemStack(Material.EMERALD_BLOCK)).addRecipe(new ItemStack(Material.DIAMOND, 9), new ItemStack(Material.DIAMOND_BLOCK)).addRecipe(new ItemStack(Material.GOLD_INGOT, 9), new ItemStack(Material.GOLD_BLOCK)).addRecipe(new ItemStack(Material.IRON_INGOT, 9), new ItemStack(Material.IRON_BLOCK)).addRecipe(new ItemStack(Material.NETHERITE_INGOT, 9), new ItemStack(Material.NETHERITE_BLOCK)).addRecipe(new ItemStack(Material.REDSTONE, 9), new ItemStack(Material.REDSTONE_BLOCK)).addRecipe(new ItemStack(Material.QUARTZ, 9), new ItemStack(Material.QUARTZ_BLOCK)).addRecipe(new ItemStack(Material.LAPIS_LAZULI, 9), new ItemStack(Material.LAPIS_BLOCK)).addRecipe(new ItemStack(Material.COAL, 9), new ItemStack(Material.COAL_BLOCK)).addRecipe(new SlimefunItemStack(COBBLE_4, 9), COBBLE_5).addRecipe(new SlimefunItemStack(COBBLE_3, 9), COBBLE_4).addRecipe(new SlimefunItemStack(COBBLE_2, 9), COBBLE_3).addRecipe(new SlimefunItemStack(COBBLE_1, 9), COBBLE_2).addRecipe(new ItemStack(Material.COBBLESTONE, 9), COBBLE_1).ticksPerOutput(1).energyPerTick(60).register(addon);
        new GearTransformer(ADVANCED_MACHINES, GEAR_TRANSFORMER, ENHANCED_CRAFTING_TABLE, new ItemStack[]{MAGSTEEL_PLATE, MACHINE_CIRCUIT, MAGSTEEL_PLATE, MACHINE_CIRCUIT, new ItemStack(Material.SMITHING_TABLE), MACHINE_CIRCUIT, MAGSTEEL_PLATE, MACHINE_CIRCUIT, MAGSTEEL_PLATE}, GEAR_TRANSFORMER_ENERGY).register(addon);
        new GeoQuarry(ADVANCED_MACHINES, GEO_QUARRY, ENHANCED_CRAFTING_TABLE, new ItemStack[]{MACHINE_PLATE, VOID_INGOT, MACHINE_PLATE, VOID_INGOT, ADVANCED_GEO_MINER, VOID_INGOT, MACHINE_PLATE, VOID_INGOT, MACHINE_PLATE,}).ticksPerOutput(GEO_QUARRY_INTERVAL).energyPerTick(GEO_QUARRY_ENERGY).register(addon);
    }

    static final class RandomizedItemStack extends ItemStack {
        final ItemStack[] items;

        public RandomizedItemStack(ItemStack... outputs) {
            super(outputs[0]);
            this.items = outputs;
        }

        @org.jetbrains.annotations.NotNull
        @Override
        public ItemStack clone() {
            return this.items[java.util.concurrent.ThreadLocalRandom.current().nextInt(this.items.length)].clone();
        }
    }
}